# Более продвинутая версия с сохранением отчета в файл
stages:
  - lint

ruff-check:
  stage: lint
  image: python:3.11-alpine
  script:
    # Устанавливаем ruff
    - pip install ruff

    # Показываем все проблемы (но не останавливаемся на них)
    - echo "=== ПОЛНЫЙ ОТЧЕТ (ВСЕ КАТЕГОРИИ) ==="
    - ruff check . || true

    # Пустая строка для разделения
    - echo ""

    # Затем проверяем только E и завершаемся с ошибкой если они есть
    - echo "=== ФИНАЛЬНАЯ ПРОВЕРКА (ТОЛЬКО ОШИБКИ E) ==="
    - ruff check --select=E --exit-non-zero-on-fix .
  cache:
    paths:
      - .cache/ruff
    key: "${CI_COMMIT_REF_SLUG}"