variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - lint

ruff-check:
  stage: lint
  image: python:3.11-slim
  cache:
    paths:
      - .cache/pip
      - .cache/ruff
  before_script:
    - pip install ruff
  script:
    - ruff check --select=E --exit-non-zero-on-fix .
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
    expire_in: 1 week
